package Entreprise.gestion.personnel;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.Timestamp;
import java.util.Date;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 * @author Issam
 */
public class Employee extends javax.swing.JFrame {
    

    /**
     * Creates new form Stagiaire
     */
    public Employee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textcine = new javax.swing.JTextField();
        textnome = new javax.swing.JTextField();
        textprenome = new javax.swing.JTextField();
        textnaisse = new javax.swing.JTextField();
        texttele = new javax.swing.JTextField();
        textgrade = new javax.swing.JTextField();
        textsalaire = new javax.swing.JTextField();
        textfct = new javax.swing.JTextField();
        textabs = new javax.swing.JTextField();
        buttonajouter = new javax.swing.JButton();
        buttonvider = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        buttonrechercher = new javax.swing.JButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        textrecherchere = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableliste = new javax.swing.JTable();
        buttonsupprimer = new javax.swing.JButton();
        buttonaffichere = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("CIN:");
        jLabel1.setName(""); // NOI18N

        jLabel2.setText("Nom:");

        jLabel3.setText("Prenom:");

        jLabel4.setText("date-naiss:");

        jLabel5.setText("tel:");

        jLabel6.setText("grade");

        jLabel7.setText("salaire");

        jLabel8.setText("fonction");

        jLabel9.setText("nbre d'absence");

        buttonajouter.setText("Ajouter");
        buttonajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonajouterActionPerformed(evt);
            }
        });

        buttonvider.setText("Vider");
        buttonvider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonviderActionPerformed(evt);
            }
        });

        jLabel10.setText("Rechercher par");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("CIN");

        buttonrechercher.setText("Rechercher");
        buttonrechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonrechercherActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Nom");

        tableliste.setMaximumSize(new java.awt.Dimension(2000, 450));
        tableliste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablelisteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableliste);

        buttonsupprimer.setText("Supprimer");
        buttonsupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonsupprimerActionPerformed(evt);
            }
        });

        buttonaffichere.setText("Afficher la liste des employeés");
        buttonaffichere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonaffichereActionPerformed(evt);
            }
        });

        jButton1.setText("Modifier");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(buttonsupprimer, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(buttonvider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel9)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonajouter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textcine, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textnome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textprenome, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(1, 1, 1))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textnaisse, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(textgrade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5)))
                                    .addGap(57, 57, 57)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textabs, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(textsalaire)
                                            .addComponent(textfct)
                                            .addComponent(texttele, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(jLabel8)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonaffichere, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 74, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(textrecherchere, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonrechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textcine, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textnome, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(textprenome, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 116, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(textnaisse, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(texttele, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(textgrade, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textsalaire, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(textfct, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonaffichere, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textabs, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textrecherchere, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonrechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 26, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(buttonajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonvider, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(buttonsupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jRadioButton1)
                                .addGap(9, 9, 9)
                                .addComponent(jRadioButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel10)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      
        String urlpilote = "com.mysql.jdbc.Driver";
        String urlbd = "jdbc:mysql://localhost:3306/gestion_d'entreprise";
        try{
        // connexion avec base de donnée gestion d'entreprise.
        Class.forName(urlpilote);
       
        cnx = DriverManager.getConnection(urlbd,"root","");
        St = cnx.createStatement();
        buttonGroup1.add(jRadioButton1);
        buttonGroup1.add(jRadioButton2);
        jRadioButton1.setSelected(true);
        dt = new DefaultTableModel();
        dt.addColumn("cin");
        dt.addColumn("nom");
        dt.addColumn("prenom");
        dt.addColumn("dateNaiss");
        dt.addColumn("tel");
        dt.addColumn("grade");
        dt.addColumn("salaire");
        dt.addColumn("fonction");
        dt.addColumn("nbre abs");
        tableliste.setModel(dt);
        // afficehr la liste des stagiaires
        AfficherEmployee();
        
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur de connexion\n"+e.getMessage());
    }
    }//GEN-LAST:event_formWindowOpened

    private void buttonajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonajouterActionPerformed
        try{
        // verifier si deja exist
        boolean b = false;
        for(int j=0; j < dt.getRowCount() ;j++){
            if(Integer.parseInt(textcine.getText()) <1 && Integer.parseInt(textcine.getText())>99999999){
                b = true;
                break;
            }
        }
        if(b == false && (textcine.getText()!="" || textnome.getText()!="" || textprenome.getText()!="" || texttele.getText()!=""|| textnaisse.getText()!="" || textgrade.getText()!="" || textsalaire.getText()!="" || textfct.getText()!="" || textabs.getText()!="")){
            St.executeUpdate("Insert into employee Values("+textcine.getText()+",'"+textnome.getText()+"','"+textprenome.getText()+"',"+texttele.getText()+",'"+textnaisse.getText()+"','"+textgrade.getText()+"','"+textsalaire.getText()+"','"+textfct.getText()+"','"+textabs.getText()+"')");
            AfficherEmployee(); // recharger la liste des stagiaires
            JOptionPane.showMessageDialog(null, "L'employeé est ajouté");
            textcine.setText("");
            textnome.setText("");
            textprenome.setText("");
            texttele.setText("");
            textnaisse.setText("");
            textgrade.setText("");
            textsalaire.setText("");
            textfct.setText("");
            textabs.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Il faut remplir tous les champs avec des valeurs valide!");    
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Il faut remplir tous les champs avec des valeurs valide\n");
    }    
    }//GEN-LAST:event_buttonajouterActionPerformed

    private void buttonviderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonviderActionPerformed
        textcine.setText("");
        textnome.setText("");
        textprenome.setText("");
        texttele.setText("");
        textnaisse.setText("");
        textgrade.setText("");
        textsalaire.setText("");
        textfct.setText("");
        textabs.setText("");
    }//GEN-LAST:event_buttonviderActionPerformed

    private void tablelisteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablelisteMouseClicked
         try{
        int i = tableliste.getSelectedRow();
        DeplacerEmployee(i);
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur selectionnéé \n"+e.getMessage());
    }
    }//GEN-LAST:event_tablelisteMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{ 
        if (JOptionPane.showConfirmDialog(null, "confirmer la modification","modification",JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION){
            St.executeUpdate("UPDATE employee SET nom='"+textnome.getText()+"',prenom='"+textprenome.getText()+"',tel='"+texttele.getText()+"',date_naiss='"+textnaisse.getText()+"',grade='"+textgrade.getText()+"',salaire='"+textsalaire.getText()+"',fonction='"+textfct.getText()+"',absence='"+textabs.getText()+"' WHERE cin = "+ textcine.getText());                                
            AfficherEmployee(); // recharger la liste des employeés
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur de modification\n"+e.getMessage());
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonsupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonsupprimerActionPerformed
         try{
         
        if(JOptionPane.showConfirmDialog(null, "Confirmer la suppression","Supprimer base",JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION){
            if(textcine.getText().length() != 0){
                St.executeUpdate("Delete from employee where cin = "+ textcine.getText());
                AfficherEmployee(); // recharger la liste des employeés ...
            }else{
                JOptionPane.showMessageDialog(null, "veuillez remplir champ cin !");
            }
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur de suppression  !\n"+e.getMessage());
    }
    }//GEN-LAST:event_buttonsupprimerActionPerformed

    private void buttonrechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonrechercherActionPerformed
        try{
        dt.setRowCount(0); // vider la liste des stagiaires
        if(jRadioButton1.isSelected()){ // radioboutton 'mat'
            Rs = St.executeQuery("Select * From employee WHERE cin = "+textrecherchere.getText());
        }else{
            Rs = St.executeQuery("Select * From employee WHERE nom = '"+textrecherchere.getText()+"'");
        }
        while(Rs.next()){
              cin = Rs.getInt("cin");
            nom = Rs.getString("nom");
            prenom = Rs.getString("prenom");
            dateNaiss = Rs.getDate("date_naiss");
            tel = Rs.getInt("tel");
            grade = Rs.getString("grade");
            salaire = Rs.getInt("salaire");
            fonction = Rs.getString("fonction");
            abs = Rs.getInt("absence");
            Object[] stg = {cin,nom,prenom,dateNaiss,tel,grade,salaire,fonction,abs};
            dt.addRow(stg);
           
        }
        if (dt.getRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Aucun Stagiaire");
            AfficherEmployee(); // afficehr tout les employeés
        }else{
           int i = 0;
            DeplacerEmployee(i);
        }
        
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur btn rechercher stg !\n"+e.getMessage());
    }
    }//GEN-LAST:event_buttonrechercherActionPerformed

    private void buttonaffichereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonaffichereActionPerformed
        AfficherEmployee();
    }//GEN-LAST:event_buttonaffichereActionPerformed
     
    
    private void AfficherEmployee(){
    try{
        dt.setRowCount(0); // vider la list des stagiaires.
        Rs = St.executeQuery("Select * From employee");
        
        while(Rs.next()){
            cin = Rs.getInt("cin");
            nom = Rs.getString("nom");
            prenom = Rs.getString("prenom");
            dateNaiss = Rs.getDate("date_naiss");
            tel = Rs.getInt("tel");
            grade = Rs.getString("grade");
            salaire = Rs.getInt("salaire");
            fonction = Rs.getString("fonction");
            abs = Rs.getInt("absence");
            Object[] stg = {cin,nom,prenom,dateNaiss,tel,grade,salaire,fonction,abs};
            dt.addRow(stg);
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur d'affichage\n"+e.getMessage());
    }
}
    
    
    
    private void DeplacerEmployee(int i){
    try{
        if (dt.getRowCount() == 0){
            
        textcine.setText("");
        textnome.setText("");
        textprenome.setText("");
        texttele.setText("");
        textnaisse.setText("");
        textgrade.setText("");
        textsalaire.setText("");
        textfct.setText("");
        textabs.setText("");
        }else{
            
        
        textcine.setText(dt.getValueAt(i, 0).toString()); // i represente numero d ligne ,et 0 1 .. colonne
        textnome.setText(dt.getValueAt(i, 1).toString());
        textprenome.setText(dt.getValueAt(i, 2).toString());
        textnaisse.setText(dt.getValueAt(i, 3).toString());
        texttele.setText(dt.getValueAt(i, 4).toString());
        textgrade.setText(dt.getValueAt(i, 5).toString());
        textsalaire.setText(dt.getValueAt(i, 6).toString());
        textfct.setText(dt.getValueAt(i, 7).toString());
        textabs.setText(dt.getValueAt(i, 8).toString());}
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur deplacement employee\n"+e.getMessage());
    }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }
    
    private Connection cnx;
    private Statement St;
    private ResultSet Rs;
    private DefaultTableModel dt;
    private int cin,tel,abs,salaire;
    private String nom ,prenom,grade,fonction;
    private Date dateNaiss;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton buttonaffichere;
    private javax.swing.JButton buttonajouter;
    private javax.swing.JButton buttonrechercher;
    private javax.swing.JButton buttonsupprimer;
    private javax.swing.JButton buttonvider;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableliste;
    private javax.swing.JTextField textabs;
    private javax.swing.JTextField textcine;
    private javax.swing.JTextField textfct;
    private javax.swing.JTextField textgrade;
    private javax.swing.JTextField textnaisse;
    private javax.swing.JTextField textnome;
    private javax.swing.JTextField textprenome;
    private javax.swing.JTextField textrecherchere;
    private javax.swing.JTextField textsalaire;
    private javax.swing.JTextField texttele;
    // End of variables declaration//GEN-END:variables
}
