package Entreprise.gestion.personnel;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.Timestamp;
import java.util.Date;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 * @author Issam
 */
public class Stagiaire extends javax.swing.JFrame {
    

    /**
     * Creates new form Stagiaire
     */
    public Stagiaire() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textcin = new javax.swing.JTextField();
        textnom = new javax.swing.JTextField();
        textprenom = new javax.swing.JTextField();
        textnaiss = new javax.swing.JTextField();
        texttel = new javax.swing.JTextField();
        textts = new javax.swing.JTextField();
        textds = new javax.swing.JTextField();
        textfs = new javax.swing.JTextField();
        textuniv = new javax.swing.JTextField();
        buttonajouter = new javax.swing.JButton();
        buttonvider = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        buttonrechercher = new javax.swing.JButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        textrechercher = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablelist = new javax.swing.JTable();
        buttonsupprimer = new javax.swing.JButton();
        buttonafficher = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("CIN:");
        jLabel1.setName(""); // NOI18N

        jLabel2.setText("Nom:");

        jLabel3.setText("Prenom:");

        jLabel4.setText("date-naiss:");

        jLabel5.setText("tel:");

        jLabel6.setText("titre de stage:");

        jLabel7.setText("debut de stage:");

        jLabel8.setText("fin de stage:");

        jLabel9.setText("université:");

        buttonajouter.setText("Ajouter");
        buttonajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonajouterActionPerformed(evt);
            }
        });

        buttonvider.setText("Vider");
        buttonvider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonviderActionPerformed(evt);
            }
        });

        jLabel10.setText("Rechercher par");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("CIN");

        buttonrechercher.setText("Rechercher");
        buttonrechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonrechercherActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Nom");

        tablelist.setMaximumSize(new java.awt.Dimension(2000, 450));
        tablelist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablelistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablelist);

        buttonsupprimer.setText("Supprimer");
        buttonsupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonsupprimerActionPerformed(evt);
            }
        });

        buttonafficher.setText("Afficher la liste des stagiaires");
        buttonafficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonafficherActionPerformed(evt);
            }
        });

        jButton1.setText("Modifier");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(buttonsupprimer, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel9))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(buttonvider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonajouter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel1))
                                    .addComponent(jLabel2))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addComponent(textprenom, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textcin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textnom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textnaiss, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textts, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(57, 57, 57))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addGap(18, 18, 18)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textuniv, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(textds)
                                            .addComponent(textfs)
                                            .addComponent(texttel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonafficher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 74, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(textrechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonrechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textcin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textnom, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(textprenom, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 116, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(textnaiss, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(texttel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(textts, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textds, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(textfs, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonafficher, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textuniv, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textrechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonrechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 26, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(buttonajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonvider, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(buttonsupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jRadioButton1)
                                .addGap(9, 9, 9)
                                .addComponent(jRadioButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel10)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      
        String urlpilote = "com.mysql.jdbc.Driver";
        String urlbd = "jdbc:mysql://localhost:3306/gestion_d'entreprise";
        try{
        // connexion avec base de donnée stg.
        Class.forName(urlpilote);
        
        
        // specify url, username, pasword - make sure these are valid 
        //cnx = DriverManager.getConnection(url, "", "");
       
        cnx = DriverManager.getConnection(urlbd,"root","");
        St = cnx.createStatement();
        buttonGroup1.add(jRadioButton1);
        buttonGroup1.add(jRadioButton2);
        jRadioButton1.setSelected(true);
        dt = new DefaultTableModel();
        dt.addColumn("cin");
        dt.addColumn("nom");
        dt.addColumn("prenom");
        dt.addColumn("dateNaiss");
        dt.addColumn("tel");
        dt.addColumn("titre de stage");
        dt.addColumn("debut de stage");
        dt.addColumn("fin de stage");
        dt.addColumn("universite");
        tablelist.setModel(dt);
        // afficehr la liste des stagiaires
        AfficherStagiaire();
        // remplir les champs 
       // i = 0;
        //DeplacerStagiaire(i);
        
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur de connexion\n"+e.getMessage());
    }
    }//GEN-LAST:event_formWindowOpened

    private void buttonajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonajouterActionPerformed
        try{
        // verifier si deja exist
        boolean b = false;
        for(int j=0; j < dt.getRowCount() ;j++){
            if(Integer.parseInt(textcin.getText()) <1 && Integer.parseInt(textcin.getText())>99999999){
                b = true;
                
                break;
            }
        }
        if(b == false && (textcin.getText()!="" || textnom.getText()!="" || textprenom.getText()!="" || texttel.getText()!=""|| textnaiss.getText()!="" || textts.getText()!="" || textds.getText()!="" || textfs.getText()!="" || textuniv.getText()!="")){
            St.executeUpdate("Insert into stagiaire Values("+textcin.getText()+",'"+textnom.getText()+"','"+textprenom.getText()+"',"+texttel.getText()+",'"+textnaiss.getText()+"','"+textts.getText()+"','"+textds.getText()+"','"+textfs.getText()+"','"+textuniv.getText()+"')");
            AfficherStagiaire(); // recharger la liste des stagiaires
            JOptionPane.showMessageDialog(null, "Le stagiaire est ajouté");
            textcin.setText("");
            textnom.setText("");
            textprenom.setText("");
            texttel.setText("");
            textnaiss.setText("");
            textts.setText("");
            textds.setText("");
            textfs.setText("");
            textuniv.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Il faut remplir tous les champs avec des valeurs valide!");
            
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Il faut remplir tous les champs avec des valeurs valide\n");
    }
        
    }//GEN-LAST:event_buttonajouterActionPerformed

    private void buttonviderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonviderActionPerformed
        textcin.setText("");
        textnom.setText("");
        textprenom.setText("");
        texttel.setText("");
        textnaiss.setText("");
        textts.setText("");
        textds.setText("");
        textfs.setText("");
        textuniv.setText("");
    }//GEN-LAST:event_buttonviderActionPerformed

    private void tablelistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablelistMouseClicked
         try{
        int i = tablelist.getSelectedRow();
        DeplacerStagiaire(i);
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur selectionnéé \n"+e.getMessage());
    }
    }//GEN-LAST:event_tablelistMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{ 
        if (JOptionPane.showConfirmDialog(null, "confirmer la modification","modification",JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION){
            St.executeUpdate("UPDATE stagiaire SET nom='"+textnom.getText()+"',prenom='"+textprenom.getText()+"',tel='"+texttel.getText()+"',date_naiss='"+textnaiss.getText()+"',titre_de_stage='"+textts.getText()+"',debut_de_stage='"+textds.getText()+"',fin_de_stage='"+textfs.getText()+"',universite='"+textuniv.getText()+"' WHERE cin = "+ textcin.getText());                                
            AfficherStagiaire(); // recharger la liste des stagiaires
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur modifier base\n"+e.getMessage());
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonsupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonsupprimerActionPerformed
         try{
         
        if(JOptionPane.showConfirmDialog(null, "Confirmer la suppression","Supprimer base",JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION){
            if(textcin.getText().length() != 0){
                St.executeUpdate("Delete from stagiaire where cin = "+ textcin.getText());
                AfficherStagiaire(); // recharger la liste des stagiaires ...
            }else{
                JOptionPane.showMessageDialog(null, "veuillez remplir champ cin !");
            }
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur supprimer  !\n"+e.getMessage());
    }
    }//GEN-LAST:event_buttonsupprimerActionPerformed

    private void buttonrechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonrechercherActionPerformed
        try{
        dt.setRowCount(0); // vider la liste des stagiaires
        if(jRadioButton1.isSelected()){ // radioboutton 'mat'
            Rs = St.executeQuery("Select * From stagiaire WHERE cin = "+textrechercher.getText());
        }else{
            Rs = St.executeQuery("Select * From stagiaire WHERE nom = '"+textrechercher.getText()+"'");
        }
        while(Rs.next()){
              cin = Rs.getInt("cin");
            nom = Rs.getString("nom");
            prenom = Rs.getString("prenom");
            dateNaiss = Rs.getDate("date_naiss");
            tel = Rs.getInt("tel");
            ts = Rs.getString("titre_de_stage");
            ds = Rs.getDate("debut_de_stage");
            fs = Rs.getDate("fin_de_stage");
            univ = Rs.getString("universite");
            Object[] stg = {cin,nom,prenom,dateNaiss,tel,ts,ds,fs,univ};
            dt.addRow(stg);
           
        }
        if (dt.getRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Aucun Stagiaire");
            AfficherStagiaire(); // afficehr tout les stgs
        }else{
           int i = 0;
            DeplacerStagiaire(i);
        }
        
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur btn rechercher stg !\n"+e.getMessage());
    }
    }//GEN-LAST:event_buttonrechercherActionPerformed

    private void buttonafficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonafficherActionPerformed
        AfficherStagiaire();
    }//GEN-LAST:event_buttonafficherActionPerformed
     
    
    private void AfficherStagiaire(){
    try{
        dt.setRowCount(0); // vider la list des stagiaires.
        Rs = St.executeQuery("Select * From stagiaire");
        
        while(Rs.next()){
            cin = Rs.getInt("cin");
            nom = Rs.getString("nom");
            prenom = Rs.getString("prenom");
            dateNaiss = Rs.getDate("date_naiss");
            tel = Rs.getInt("tel");
            ts = Rs.getString("titre_de_stage");
            ds = Rs.getDate("debut_de_stage");
            fs = Rs.getDate("fin_de_stage");
            univ = Rs.getString("universite");
            Object[] stg = {cin,nom,prenom,dateNaiss,tel,ts,ds,fs,univ};
            dt.addRow(stg);
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur afficher la liste des stagiaire\n"+e.getMessage());
    }
}
    
    
    
    private void DeplacerStagiaire(int i){
    try{
        if (dt.getRowCount() == 0){
            
        textcin.setText("");
        textnom.setText("");
        textprenom.setText("");
        texttel.setText("");
        textnaiss.setText("");
        textts.setText("");
        textds.setText("");
        textfs.setText("");
        textuniv.setText("");
        }else{
            
        
        textcin.setText(dt.getValueAt(i, 0).toString()); // i represente numero d ligne ,et 0 1 .. colonne
        textnom.setText(dt.getValueAt(i, 1).toString());
        textprenom.setText(dt.getValueAt(i, 2).toString());
        textnaiss.setText(dt.getValueAt(i, 3).toString());
        texttel.setText(dt.getValueAt(i, 4).toString());
        textts.setText(dt.getValueAt(i, 5).toString());
        textds.setText(dt.getValueAt(i, 6).toString());
        textfs.setText(dt.getValueAt(i, 7).toString());
        textuniv.setText(dt.getValueAt(i, 8).toString());}
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur deplacement stagiaire\n"+e.getMessage());
    }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Stagiaire().setVisible(true);
            }
        });
    }
    
    private Connection cnx;
    private Statement St;
    private ResultSet Rs;
    private DefaultTableModel dt;
    private int cin,tel;
    private String nom ,prenom,ts,univ;
    private Date dateNaiss, ds ,fs;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton buttonafficher;
    private javax.swing.JButton buttonajouter;
    private javax.swing.JButton buttonrechercher;
    private javax.swing.JButton buttonsupprimer;
    private javax.swing.JButton buttonvider;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablelist;
    private javax.swing.JTextField textcin;
    private javax.swing.JTextField textds;
    private javax.swing.JTextField textfs;
    private javax.swing.JTextField textnaiss;
    private javax.swing.JTextField textnom;
    private javax.swing.JTextField textprenom;
    private javax.swing.JTextField textrechercher;
    private javax.swing.JTextField texttel;
    private javax.swing.JTextField textts;
    private javax.swing.JTextField textuniv;
    // End of variables declaration//GEN-END:variables
}
